### ISSUE TITLE
Issues with Readthedocs documentation

### ISSUE THREAD

**Issue by chmreid** [HumanCellAtlas/dcp-cli#443]
There are some issues in the HCA CLI docs on readthedocs (https://hca.readthedocs.io/en/latest/cli.html):

- [x] <s>"Named Arguments" section, the options listed for `--log-level` look weird (inconsistent font and size)</s> This is just the readthedocs style - flag descriptions extending over multiple lines have different font sizes than descriptions on a single line
- [x] <s>"forget" and "creds" subcommand flags don't have `--` (`uuid_or_alias` instead of `--uuid-or-alias`). Are these flags?</s> The `uuid_or_alias` args for these subcommands are positional args and not flags.
- [x] <s>"report" subcommand flags have long versions prefixed with `-` (one hyphen) instead of `--` (two hyphens). This is the only subcommand that doesn't follow the convention</s> PR #480 ensures args start with two dashes `--` and not single dash `-`
- [x] <s>"select", "files", and other sub-commands (https://hca.readthedocs.io/en/latest/cli.html#select) have their documentation created directly from docstrings. Unfortunately, this also includes the four spaces prefixing the docstring, so documentation drawn directly from docstrings is formatted as a code block</s> addressed by #479
- [x] <s>More inconsistent text formatting in some tables (e.g., https://hca.readthedocs.io/en/latest/cli.html#Named%20Arguments_repeat1)</s> This is just the readthedocs style
- [ ] The "areas" subcommand has a weird docstring: "List upload areas I know about." Documentation should not be in first person.
- [x] <s>"creds" subcommand capitalizes "upload area", no one else does (https://hca.readthedocs.io/en/latest/cli.html#creds)</s> addressed by #479
- [x] <s>More inconsistent font sizes in table here (https://hca.readthedocs.io/en/latest/cli.html#Named%20Arguments_repeat7)</s> This is the readthedocs style - descriptions on a single line have a smaller font size than descriptions extending over multiple lines
- [ ] The "form fields" argument listed here (https://hca.readthedocs.io/en/latest/cli.html#Named%20Arguments_repeat21) seems to have something weird going on
with `2769baffc4f24cbc83ced26aa0c2f712`
- [ ] Fixmes and Todos left over here: https://hca.readthedocs.io/en/latest/cli.html#post-bundles-checkout
- [x] <s>get-collections and put-collections (and some other subcommands) seem to share a lot of copypasta (https://hca.readthedocs.io/en/latest/cli.html#get-collections)</s> Documentation for these functions is automatically generated from the DSS swagger file, which is where the redundancy comes from
- [x] <s>Double-periods in this item (https://hca.readthedocs.io/en/latest/cli.html#download-manifest)</s> addressed by #460
- [ ] The CLI documentation (https://hca.readthedocs.io/en/latest/cli.html#cli-documentation) has `{prog}` that should be replaced with `hca`. The substitution happens in the command line utility help docstring, but it does not happen for the ReadTheDocs documentation.

**Comment by chmreid** [comment]
Re the `areas` subcommand - what is an upload area? https://github.com/HumanCellAtlas/dcp-cli/blob/master/hca/upload/upload_area.py#L14
